server:
  port: 2001

spring:
  application:
    name: springcloud-seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: legend_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456


#hystrix启用feign支持
feign:
  hystrix:
    enabled: false


#seata日志
logging:
  level:
    io:
      seata: info


#Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml