server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址
        server-addr: 192.168.0.120:8888 #换成nginx的8888端口做Nacos的集群


# 把监控的东西暴露出来
management:
  endpoints:
    web:
      exposure:
        include: '*'
