server:
  port: 3344

#中心化外部配置 (http://config-3344.com:3344/springcloudconfig/dev/master  or  http://config-3344.com:3344/master/springcloudconfig-dev.yml)
spring:
  application:
    name:  springcloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:qichunlin/microservicecloud-config.git # 用这个会报错的话使用下面的
          uri: https://github.com/qichunlin/microservicecloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - microservicecloud-config
      ####读取分支
      label: master


#服务注册到eureka地址
eureka:
  client:
    service-url:
      #配置单机版
      defaultZone: http://localhost:7001/eureka
      #集群版本
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    prefer-ip-address: true
    instance-id: springcloud-config




