server:
  port: 9527

#第一种路由网关配置
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://springcloud-payment-service #匹配后提供服务的路由地址  http://localhost:9527/api/payment/query/1
          predicates:
            - Path=/api/payment/query/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://springcloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/api/payment/lb/**         # 断言，路径相匹配的进行路由   http://localhost:9527/api/payment/lb
            - After=2020-04-22T12:51:37.485+08:00[Asia/Shanghai]   #  TestZone 里面的main函数可以获取 java8提供
            #- Betwen=2020-04-22T12:51:37.485+08:00[Asia/Shanghai],2020-04-25T12:51:37.485+08:00[Asia/Shanghai]   #  时间范围内可以访问
            #- Cookie=username,qcl     # curl http://localhost:9527/api/payment/lb --cookie "username=qcl"
            # curl http://localhost:9527/api/payment/lb --cookie "username=qcl" -H "X-Request-Id:123"
            #- Header=X-Request-Id, \d+  # 请求头(两个参数:一个是属性名称和一个正则表达式,这个属性值和正则表达式匹配则执行)要有X-Request-Id属性并且值为整数的正则表达式
            # curl http://localhost:9527/api/payment/lb -H "Host: www.qcl.com"
            #- Host=**.qcl.com   # 限制主机域名列表
            #- Method=GET   # get方法
            # curl http://localhost:9527/api/payment/lb?username=31 -H "Host: www.qcl.com"
            #- Query=username, \d+   # 要有参数名并且值还是要整数才能路由
eureka:
  instance:
    hostname: springcloud-gateway-service
    prefer-ip-address: true
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


